### ISSUE TITLE
Some classes are missing from theme-base

### ISSUE THREAD

**Issue by ghost** [primefaces/primevue-sass-theme#2]
`primevue/resources/primevue.css` from the the original package has some classes that are missing from this repository. for example `.p-hidden-accessible` or `.p-overflow-hidden` , so you still need to import `/node_modules/primevue/resources/primevue.min.css` in parallel with your theme.

I'm not sure this is intentional, but in the tutorial video (Create your own PrimeVue Themes) there is no mentioning of this.

Both versions are at 3.26 on my local.

**Comment by cerinoligutom** [comment]
Also encountering this issue.

**Comment by r25s** [comment]
I suspect this could be happening in my case also. I am using Nuxt and loading `theme.scss` in the nuxt configuration. So far, most things look fine. However, the floating label for the Text Input doesn't work unless I also import primevue.css.

Here is my `nuxt.config.ts` file:

```
export default defineNuxtConfig({
    css: [
        'assets/themes/material/material-dark/standard/deeppurple/theme.scss',
        'primevue/resources/primevue.css',
    ],
    build: {
        transpile: ['primevue'],
    }
})
```

Using version 3.26.1

**Comment by cerinoligutom** [comment]
It was the password component for me and it didn't look right when I tried the [Basic](https://primevue.org/password/#basic) example. The workaround that @dekztah presented works since it contains the missing classes. Particularly some classes at [Common.css](https://github.com/primefaces/primevue/blob/04af30b0153d60bda6e8a8d47939eba55d65c414/components/lib/common/Common.css)

Thought of making a PR but upon checking the other frameworks, the classes are missing as well so if this was intentional (I'd like to think otherwise) then maybe we're missing an instruction. Worst-case scenario, there are more missing classes that we  have yet to discover. 

Vue has [73 lines](https://github.com/primefaces/primevue-sass-theme/blob/9f553448741a901c7fa31573874481e6b8c76684/theme-base/_common.scss) while [React](https://github.com/primefaces/primereact-sass-theme/blob/c7dfcd16c795186413e46e9e75582b95c4733a25/theme-base/_common.scss) and [Angular](https://github.com/primefaces/primeng-sass-theme/blob/6a77803ba82296bd83a38ac357a20ec8bd7f8368/theme-base/_common.scss) has 68 lines so they're even missing one more class `.p-icon`.

**Comment by cagataycivici** [comment]
They are added dynamically after the introduction of unstyled mode as they are still used in unstyled mode as well so they moved to core.
